"""RBI regional office jurisdictions and the places that define them.

The RD View's in-region tab needs to know, for news about an entity
headquartered elsewhere, whether the story happened in this office's
region. Jurisdiction is by state, so each office maps to its state(s)
and each state to its districts and major cities -- the names a
journalist actually writes. Maharashtra is the special case: the Nagpur
office covers the Vidarbha districts and Mumbai/Belapur the rest, so
those offices carve the state between them.

Static on purpose: office jurisdictions are facts, not preferences. A
district missing here costs one missed match, never a crash -- and the
same name in two states (Aurangabad, Bilaspur, Hamirpur) simply counts
for both regions, because without more context that is the truth.
"""

# Office -> states (or carved parts of one, see the Maharashtra split).
OFFICE_STATES = {
    "Agartala": ["Tripura"],
    "Ahmedabad": ["Gujarat", "Dadra and Daman"],
    "Aizawl": ["Mizoram"],
    "Belapur": ["Maharashtra (excluding Vidarbha)"],
    "Bengaluru": ["Karnataka"],
    "Bhopal": ["Madhya Pradesh"],
    "Bhubaneswar": ["Odisha"],
    "Chandigarh": ["Punjab", "Chandigarh"],
    "Chennai": ["Tamil Nadu", "Puducherry"],
    "Dehradun": ["Uttarakhand"],
    "Gangtok": ["Sikkim"],
    "Guwahati": ["Assam"],
    "Hyderabad": ["Telangana", "Andhra Pradesh"],
    "Imphal": ["Manipur"],
    "Itanagar": ["Arunachal Pradesh"],
    "Jaipur": ["Rajasthan"],
    "Jammu": ["Jammu and Kashmir", "Ladakh"],
    "Kanpur": ["Uttar Pradesh"],
    "Kohima": ["Nagaland"],
    "Kolkata": ["West Bengal", "Andaman and Nicobar"],
    "Lucknow": ["Uttar Pradesh"],
    "Mumbai": ["Maharashtra (excluding Vidarbha)"],
    "Nagpur": ["Maharashtra (Vidarbha)"],
    "New Delhi": ["Delhi", "Haryana"],
    "Panaji": ["Goa"],
    "Patna": ["Bihar"],
    "Raipur": ["Chhattisgarh"],
    "Ranchi": ["Jharkhand"],
    "Shillong": ["Meghalaya"],
    "Shimla": ["Himachal Pradesh"],
    "Srinagar": ["Jammu and Kashmir", "Ladakh"],
    "Thiruvananthapuram": ["Kerala", "Lakshadweep"],
}

# Alternate spellings a paper might use for the state itself.
STATE_NAMES = {
    "Odisha": ["Odisha", "Orissa"],
    "Puducherry": ["Puducherry", "Pondicherry"],
    "Jammu and Kashmir": ["Jammu", "Kashmir"],
    "Andaman and Nicobar": ["Andaman", "Nicobar"],
    "Dadra and Daman": ["Daman", "Diu", "Silvassa", "Dadra"],
    "Maharashtra (Vidarbha)": ["Vidarbha"],
    "Maharashtra (excluding Vidarbha)": ["Maharashtra"],
}

_VIDARBHA = ["Nagpur", "Wardha", "Bhandara", "Gondia", "Chandrapur",
             "Gadchiroli", "Amravati", "Akola", "Washim", "Buldhana",
             "Yavatmal"]

_MAHA_REST = ["Mumbai", "Thane", "Palghar", "Raigad", "Ratnagiri",
              "Sindhudurg", "Pune", "Satara", "Sangli", "Solapur",
              "Kolhapur", "Nashik", "Ahmednagar", "Ahilyanagar", "Dhule",
              "Nandurbar", "Jalgaon", "Aurangabad",
              "Chhatrapati Sambhajinagar", "Sambhajinagar", "Jalna",
              "Beed", "Latur", "Osmanabad", "Dharashiv", "Nanded",
              "Parbhani", "Hingoli", "Navi Mumbai"]

STATE_DISTRICTS = {
    "Maharashtra (Vidarbha)": _VIDARBHA,
    "Maharashtra (excluding Vidarbha)": _MAHA_REST,
    "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar",
        "Jamnagar", "Junagadh", "Gandhinagar", "Kutch", "Bhuj", "Mehsana",
        "Patan", "Banaskantha", "Palanpur", "Sabarkantha", "Himmatnagar",
        "Aravalli", "Anand", "Kheda", "Nadiad", "Panchmahal", "Godhra",
        "Dahod", "Mahisagar", "Bharuch", "Narmada", "Navsari", "Valsad",
        "Vapi", "Tapi", "Dang", "Surendranagar", "Morbi", "Botad",
        "Amreli", "Gir Somnath", "Porbandar", "Dwarka", "Chhota Udepur"],
    "Uttar Pradesh": ["Lucknow", "Kanpur", "Agra", "Varanasi", "Prayagraj",
        "Allahabad", "Meerut", "Ghaziabad", "Noida", "Aligarh", "Bareilly",
        "Moradabad", "Saharanpur", "Gorakhpur", "Jhansi", "Mathura",
        "Firozabad", "Ayodhya", "Faizabad", "Rampur", "Shahjahanpur",
        "Muzaffarnagar", "Bulandshahr", "Etawah", "Mainpuri", "Etah",
        "Badaun", "Pilibhit", "Sitapur", "Hardoi", "Unnao", "Rae Bareli",
        "Fatehpur", "Banda", "Hamirpur", "Mahoba", "Chitrakoot", "Jalaun",
        "Lalitpur", "Kannauj", "Farrukhabad", "Auraiya", "Amethi",
        "Sultanpur", "Pratapgarh", "Kaushambi", "Mirzapur", "Sonbhadra",
        "Bhadohi", "Chandauli", "Ghazipur", "Jaunpur", "Azamgarh", "Mau",
        "Ballia", "Deoria", "Kushinagar", "Maharajganj", "Basti",
        "Siddharthnagar", "Gonda", "Balrampur", "Bahraich", "Shravasti",
        "Ambedkar Nagar", "Barabanki", "Lakhimpur Kheri", "Hathras",
        "Kasganj", "Sambhal", "Amroha", "Bijnor", "Shamli", "Baghpat",
        "Hapur"],
    "Karnataka": ["Bengaluru", "Bangalore", "Mysuru", "Mysore",
        "Mangaluru", "Mangalore", "Hubballi", "Hubli", "Dharwad",
        "Belagavi", "Belgaum", "Ballari", "Bellary", "Vijayapura",
        "Kalaburagi", "Gulbarga", "Davangere", "Shivamogga", "Shimoga",
        "Tumakuru", "Tumkur", "Udupi", "Hassan", "Mandya",
        "Chikkamagaluru", "Kolar", "Chikkaballapur", "Ramanagara",
        "Chitradurga", "Haveri", "Gadag", "Koppal", "Raichur", "Bidar",
        "Yadgir", "Bagalkot", "Uttara Kannada", "Karwar",
        "Dakshina Kannada", "Kodagu", "Chamarajanagar"],
    "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli",
        "Trichy", "Salem", "Tirunelveli", "Erode", "Vellore",
        "Thoothukudi", "Tuticorin", "Thanjavur", "Dindigul",
        "Kanyakumari", "Karur", "Namakkal", "Krishnagiri", "Dharmapuri",
        "Villupuram", "Cuddalore", "Chengalpattu", "Kancheepuram",
        "Tiruvallur", "Tiruvannamalai", "Ranipet", "Tirupattur",
        "Tenkasi", "Virudhunagar", "Ramanathapuram", "Sivaganga",
        "Pudukkottai", "Ariyalur", "Perambalur", "Nagapattinam",
        "Mayiladuthurai", "Tiruvarur", "Nilgiris", "Ooty", "Theni",
        "Tirupur", "Kallakurichi"],
    "Telangana": ["Hyderabad", "Secunderabad", "Warangal", "Nizamabad",
        "Karimnagar", "Khammam", "Mahbubnagar", "Nalgonda", "Adilabad",
        "Medak", "Rangareddy", "Siddipet", "Suryapet", "Jagtial",
        "Mancherial", "Kamareddy", "Vikarabad", "Sangareddy", "Medchal",
        "Nagarkurnool", "Wanaparthy", "Gadwal", "Narayanpet",
        "Mahabubabad", "Bhupalpally", "Mulugu", "Asifabad", "Nirmal",
        "Peddapalli", "Sircilla", "Jangaon", "Bhongir"],
    "Andhra Pradesh": ["Visakhapatnam", "Vizag", "Vijayawada", "Guntur",
        "Nellore", "Kurnool", "Tirupati", "Kadapa", "Anantapur",
        "Chittoor", "Rajahmundry", "Rajamahendravaram", "Kakinada",
        "Eluru", "Ongole", "Srikakulam", "Vizianagaram", "Machilipatnam",
        "Krishna", "East Godavari", "West Godavari", "Prakasam",
        "Annamayya", "Bapatla", "Palnadu", "Anakapalli", "Parvathipuram",
        "Nandyal"],
    "Kerala": ["Thiruvananthapuram", "Kollam", "Pathanamthitta",
        "Alappuzha", "Kottayam", "Idukki", "Ernakulam", "Kochi",
        "Thrissur", "Palakkad", "Malappuram", "Kozhikode", "Wayanad",
        "Kannur", "Kasaragod"],
    "West Bengal": ["Kolkata", "Howrah", "Hooghly", "Asansol", "Durgapur",
        "Siliguri", "Darjeeling", "Kalimpong", "Jalpaiguri",
        "Alipurduar", "Cooch Behar", "Malda", "Murshidabad",
        "Berhampore", "Nadia", "Krishnanagar", "Barasat", "Bardhaman",
        "Burdwan", "Birbhum", "Bankura", "Purulia", "Midnapore",
        "Paschim Medinipur", "Purba Medinipur", "Haldia", "Jhargram",
        "Raiganj", "Balurghat", "Parganas"],
    "Odisha": ["Bhubaneswar", "Cuttack", "Rourkela", "Sambalpur",
        "Berhampur", "Brahmapur", "Puri", "Balasore", "Baleswar",
        "Bhadrak", "Angul", "Dhenkanal", "Kendrapara", "Jagatsinghpur",
        "Jajpur", "Keonjhar", "Mayurbhanj", "Baripada", "Koraput",
        "Rayagada", "Nabarangpur", "Malkangiri", "Kalahandi",
        "Bhawanipatna", "Bolangir", "Balangir", "Sonepur", "Bargarh",
        "Jharsuguda", "Sundargarh", "Deogarh", "Boudh", "Kandhamal",
        "Phulbani", "Gajapati", "Ganjam", "Nayagarh", "Khordha",
        "Nuapada"],
    "Madhya Pradesh": ["Bhopal", "Indore", "Gwalior", "Jabalpur",
        "Ujjain", "Sagar", "Rewa", "Satna", "Ratlam", "Dewas", "Katni",
        "Chhindwara", "Vidisha", "Sehore", "Raisen", "Hoshangabad",
        "Narmadapuram", "Betul", "Harda", "Khandwa", "Khargone",
        "Burhanpur", "Barwani", "Dhar", "Jhabua", "Alirajpur",
        "Mandsaur", "Neemuch", "Shajapur", "Agar Malwa", "Rajgarh",
        "Guna", "Ashoknagar", "Shivpuri", "Datia", "Bhind", "Morena",
        "Sheopur", "Tikamgarh", "Chhatarpur", "Panna", "Damoh",
        "Narsinghpur", "Seoni", "Mandla", "Dindori", "Balaghat",
        "Shahdol", "Umaria", "Anuppur", "Sidhi", "Singrauli", "Maihar",
        "Niwari"],
    "Chhattisgarh": ["Raipur", "Bilaspur", "Durg", "Bhilai", "Korba",
        "Rajnandgaon", "Raigarh", "Jagdalpur", "Bastar", "Ambikapur",
        "Surguja", "Dhamtari", "Mahasamund", "Kanker", "Kawardha",
        "Janjgir", "Champa", "Mungeli", "Balod", "Baloda Bazar",
        "Bemetara", "Gariaband", "Kondagaon", "Sukma", "Dantewada",
        "Narayanpur", "Jashpur", "Koriya", "Surajpur"],
    "Rajasthan": ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Ajmer",
        "Bikaner", "Alwar", "Bharatpur", "Sikar", "Jhunjhunu", "Churu",
        "Ganganagar", "Hanumangarh", "Nagaur", "Pali", "Barmer",
        "Jaisalmer", "Jalore", "Sirohi", "Bhilwara", "Chittorgarh",
        "Rajsamand", "Dungarpur", "Banswara", "Baran", "Bundi",
        "Jhalawar", "Sawai Madhopur", "Karauli", "Dholpur", "Dausa",
        "Tonk"],
    "Punjab": ["Ludhiana", "Amritsar", "Jalandhar", "Patiala",
        "Bathinda", "Mohali", "Hoshiarpur", "Gurdaspur", "Pathankot",
        "Ferozepur", "Firozpur", "Fazilka", "Faridkot", "Muktsar",
        "Moga", "Barnala", "Sangrur", "Malerkotla", "Mansa",
        "Kapurthala", "Nawanshahr", "Rupnagar", "Ropar",
        "Fatehgarh Sahib", "Tarn Taran"],
    "Haryana": ["Gurugram", "Gurgaon", "Faridabad", "Panipat", "Ambala",
        "Yamunanagar", "Rohtak", "Hisar", "Karnal", "Sonipat",
        "Panchkula", "Bhiwani", "Sirsa", "Jind", "Kaithal",
        "Kurukshetra", "Fatehabad", "Rewari", "Mahendragarh", "Narnaul",
        "Jhajjar", "Palwal", "Nuh", "Mewat", "Charkhi Dadri"],
    "Himachal Pradesh": ["Shimla", "Mandi", "Kangra", "Dharamshala",
        "Solan", "Kullu", "Manali", "Hamirpur", "Una", "Bilaspur",
        "Chamba", "Sirmaur", "Nahan", "Kinnaur", "Lahaul", "Spiti",
        "Keylong"],
    "Uttarakhand": ["Dehradun", "Haridwar", "Rishikesh", "Roorkee",
        "Nainital", "Haldwani", "Udham Singh Nagar", "Rudrapur",
        "Almora", "Pithoragarh", "Champawat", "Bageshwar", "Chamoli",
        "Rudraprayag", "Tehri", "Pauri", "Uttarkashi"],
    "Delhi": ["Delhi", "New Delhi"],
    "Bihar": ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Darbhanga",
        "Purnia", "Ara", "Arrah", "Bhojpur", "Begusarai", "Katihar",
        "Munger", "Chhapra", "Saran", "Samastipur", "Motihari",
        "Champaran", "Bettiah", "Siwan", "Gopalganj", "Vaishali",
        "Hajipur", "Sitamarhi", "Sheohar", "Madhubani", "Supaul",
        "Araria", "Kishanganj", "Madhepura", "Saharsa", "Khagaria",
        "Nalanda", "Biharsharif", "Nawada", "Jehanabad", "Arwal",
        "Aurangabad", "Jamui", "Lakhisarai", "Sheikhpura", "Banka",
        "Rohtas", "Sasaram", "Buxar", "Kaimur"],
    "Jharkhand": ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Deoghar",
        "Hazaribagh", "Giridih", "Dumka", "Palamu", "Daltonganj",
        "Chatra", "Koderma", "Jamtara", "Sahibganj", "Pakur", "Godda",
        "Lohardaga", "Gumla", "Simdega", "Khunti", "Saraikela",
        "Chaibasa", "Singhbhum", "Ramgarh", "Latehar", "Garhwa"],
    "Assam": ["Guwahati", "Dispur", "Dibrugarh", "Silchar", "Jorhat",
        "Tezpur", "Nagaon", "Tinsukia", "Bongaigaon", "Dhubri",
        "Goalpara", "Barpeta", "Nalbari", "Kamrup", "Darrang",
        "Mangaldoi", "Sonitpur", "Lakhimpur", "Dhemaji", "Majuli",
        "Sivasagar", "Golaghat", "Karbi Anglong", "Diphu", "Dima Hasao",
        "Haflong", "Cachar", "Karimganj", "Hailakandi", "Morigaon",
        "Baksa", "Chirang", "Kokrajhar", "Udalguri", "Biswanath",
        "Hojai", "Charaideo"],
    "Tripura": ["Agartala", "Dharmanagar", "Kailashahar", "Ambassa",
        "Khowai", "Belonia", "Sabroom", "Sonamura", "Bishalgarh"],
    "Manipur": ["Imphal", "Churachandpur", "Thoubal", "Bishnupur",
        "Ukhrul", "Senapati", "Tamenglong", "Chandel", "Jiribam",
        "Kangpokpi", "Kakching", "Tengnoupal", "Kamjong", "Noney",
        "Pherzawl"],
    "Meghalaya": ["Shillong", "Tura", "Jowai", "Nongpoh", "Nongstoin",
        "Williamnagar", "Baghmara", "Resubelpara", "Mairang",
        "Khliehriat", "Ampati"],
    "Mizoram": ["Aizawl", "Lunglei", "Champhai", "Serchhip", "Kolasib",
        "Mamit", "Lawngtlai", "Saiha", "Siaha", "Khawzawl", "Saitual",
        "Hnahthial"],
    "Nagaland": ["Kohima", "Dimapur", "Mokokchung", "Tuensang", "Mon",
        "Wokha", "Zunheboto", "Phek", "Kiphire", "Longleng", "Peren",
        "Noklak", "Chumoukedima", "Niuland", "Tseminyu", "Shamator"],
    "Arunachal Pradesh": ["Itanagar", "Naharlagun", "Tawang", "Bomdila",
        "Ziro", "Pasighat", "Tezu", "Roing", "Aalo", "Along", "Daporijo",
        "Seppa", "Changlang", "Khonsa", "Longding", "Anini", "Yingkiong",
        "Basar", "Namsai"],
    "Sikkim": ["Gangtok", "Namchi", "Gyalshing", "Mangan", "Pakyong",
        "Soreng"],
    "Goa": ["Panaji", "Margao", "Vasco", "Mapusa", "Ponda", "North Goa",
        "South Goa"],
    "Jammu and Kashmir": ["Srinagar", "Jammu", "Anantnag", "Baramulla",
        "Budgam", "Pulwama", "Kupwara", "Bandipora", "Ganderbal",
        "Kulgam", "Shopian", "Udhampur", "Kathua", "Doda", "Kishtwar",
        "Ramban", "Reasi", "Rajouri", "Poonch", "Samba"],
    "Ladakh": ["Leh", "Kargil"],
    "Puducherry": ["Puducherry", "Pondicherry", "Karaikal", "Mahe",
        "Yanam"],
    "Chandigarh": ["Chandigarh"],
    "Andaman and Nicobar": ["Port Blair", "Andaman", "Nicobar"],
    "Lakshadweep": ["Kavaratti", "Lakshadweep"],
    "Dadra and Daman": ["Daman", "Diu", "Silvassa"],
}


# Devanagari spellings of place names, for Marathi and Hindi press text
# (the two Devanagari-script languages this app fetches). Keyed by the
# English name used above; both Marathi and Hindi forms are given where
# they differ (Marathi \u0928\u093e\u0917\u092a\u0942\u0930 vs Hindi \u0928\u093e\u0917\u092a\u0941\u0930). A place whose
# Devanagari spelling is an everyday word -- \u0917\u092f\u093e (went), \u092e\u0902\u0921\u0940 (market),
# \u0915\u094b\u091f\u093e (quota), \u092c\u0938\u094d\u0924\u0940 (settlement), \u0917\u0941\u0928\u093e (times), \u092a\u0928\u094d\u0928\u093e (page), \u0927\u093e\u0930
# (stream), \u0906\u0930\u093e (saw), \u0938\u093e\u0917\u0930 (sea), \u092e\u090a (soft), \u092c\u0942\u0902\u0926\u0940 (a sweet), \u0915\u094b\u0930\u093f\u092f\u093e
# (Korea) -- gets NO Devanagari form: its English name still matches
# English text, and a common noun would flood the tab with false regions.
DEVANAGARI = {
    # Maharashtra + Goa (Marathi first, Hindi variant where different)
    "Maharashtra": ["महाराष्ट्र"], "Vidarbha": ["विदर्भ"],
    "Mumbai": ["मुंबई", "मुम्बई"], "Navi Mumbai": ["नवी मुंबई"],
    "Thane": ["ठाणे"], "Palghar": ["पालघर"], "Raigad": ["रायगड"],
    "Ratnagiri": ["रत्नागिरी"], "Sindhudurg": ["सिंधुदुर्ग"],
    "Pune": ["पुणे"], "Satara": ["सातारा"], "Sangli": ["सांगली"],
    "Solapur": ["सोलापूर", "सोलापुर"], "Kolhapur": ["कोल्हापूर", "कोल्हापुर"],
    "Nashik": ["नाशिक", "नासिक"], "Ahmednagar": ["अहमदनगर"],
    "Ahilyanagar": ["अहिल्यानगर"], "Dhule": ["धुळे", "धुले"],
    "Nandurbar": ["नंदुरबार"], "Jalgaon": ["जळगाव", "जलगांव"],
    "Aurangabad": ["औरंगाबाद"], "Sambhajinagar": ["संभाजीनगर"],
    "Jalna": ["जालना"], "Beed": ["बीड"], "Latur": ["लातूर", "लातुर"],
    "Osmanabad": ["उस्मानाबाद"], "Dharashiv": ["धाराशिव"],
    "Nanded": ["नांदेड"], "Parbhani": ["परभणी"], "Hingoli": ["हिंगोली"],
    "Nagpur": ["नागपूर", "नागपुर"], "Wardha": ["वर्धा"],
    "Bhandara": ["भंडारा"], "Gondia": ["गोंदिया"],
    "Chandrapur": ["चंद्रपूर", "चंद्रपुर"], "Gadchiroli": ["गडचिरोली"],
    "Amravati": ["अमरावती"], "Akola": ["अकोला"], "Washim": ["वाशिम"],
    "Buldhana": ["बुलढाणा"], "Yavatmal": ["यवतमाळ", "यवतमाल"],
    "Goa": ["गोवा"], "Panaji": ["पणजी"], "Margao": ["मडगाव"],
    "Mapusa": ["म्हापसा"], "Ponda": ["फोंडा"],
    # Uttar Pradesh
    "Uttar Pradesh": ["उत्तर प्रदेश"],
    "Lucknow": ["लखनऊ"], "Kanpur": ["कानपुर"], "Agra": ["आगरा"],
    "Varanasi": ["वाराणसी"], "Prayagraj": ["प्रयागराज"],
    "Allahabad": ["इलाहाबाद"], "Meerut": ["मेरठ"],
    "Ghaziabad": ["गाजियाबाद", "गाज़ियाबाद"], "Noida": ["नोएडा"],
    "Aligarh": ["अलीगढ़"], "Bareilly": ["बरेली"], "Moradabad": ["मुरादाबाद"],
    "Saharanpur": ["सहारनपुर"], "Gorakhpur": ["गोरखपुर"],
    "Jhansi": ["झांसी", "झाँसी"], "Mathura": ["मथुरा"],
    "Firozabad": ["फिरोजाबाद"], "Ayodhya": ["अयोध्या"],
    "Faizabad": ["फैजाबाद"], "Rampur": ["रामपुर"],
    "Shahjahanpur": ["शाहजहांपुर"], "Muzaffarnagar": ["मुजफ्फरनगर"],
    "Bulandshahr": ["बुलंदशहर"], "Etawah": ["इटावा"], "Mainpuri": ["मैनपुरी"],
    "Etah": ["एटा"], "Badaun": ["बदायूं", "बदायूँ"], "Pilibhit": ["पीलीभीत"],
    "Sitapur": ["सीतापुर"], "Hardoi": ["हरदोई"], "Unnao": ["उन्नाव"],
    "Rae Bareli": ["रायबरेली"], "Fatehpur": ["फतेहपुर"], "Banda": ["बांदा"],
    "Hamirpur": ["हमीरपुर"], "Mahoba": ["महोबा"], "Chitrakoot": ["चित्रकूट"],
    "Jalaun": ["जालौन"], "Lalitpur": ["ललितपुर"], "Kannauj": ["कन्नौज"],
    "Farrukhabad": ["फर्रुखाबाद"], "Auraiya": ["औरैया"], "Amethi": ["अमेठी"],
    "Sultanpur": ["सुल्तानपुर"], "Pratapgarh": ["प्रतापगढ़"],
    "Kaushambi": ["कौशांबी"], "Mirzapur": ["मिर्जापुर"],
    "Sonbhadra": ["सोनभद्र"], "Bhadohi": ["भदोही"], "Chandauli": ["चंदौली"],
    "Ghazipur": ["गाजीपुर"], "Jaunpur": ["जौनपुर"], "Azamgarh": ["आजमगढ़"],
    "Ballia": ["बलिया"], "Deoria": ["देवरिया"], "Kushinagar": ["कुशीनगर"],
    "Maharajganj": ["महाराजगंज"], "Siddharthnagar": ["सिद्धार्थनगर"],
    "Gonda": ["गोंडा"], "Balrampur": ["बलरामपुर"], "Bahraich": ["बहराइच"],
    "Shravasti": ["श्रावस्ती"], "Ambedkar Nagar": ["अंबेडकर नगर"],
    "Barabanki": ["बाराबंकी"], "Lakhimpur Kheri": ["लखीमपुर खीरी"],
    "Hathras": ["हाथरस"], "Kasganj": ["कासगंज"], "Sambhal": ["संभल"],
    "Amroha": ["अमरोहा"], "Bijnor": ["बिजनौर"], "Shamli": ["शामली"],
    "Baghpat": ["बागपत"], "Hapur": ["हापुड़"],
    # Madhya Pradesh
    "Madhya Pradesh": ["मध्य प्रदेश", "मध्यप्रदेश"],
    "Bhopal": ["भोपाल"], "Indore": ["इंदौर"], "Gwalior": ["ग्वालियर"],
    "Jabalpur": ["जबलपुर"], "Ujjain": ["उज्जैन"], "Rewa": ["रीवा"],
    "Satna": ["सतना"], "Ratlam": ["रतलाम"], "Dewas": ["देवास"],
    "Katni": ["कटनी"], "Chhindwara": ["छिंदवाड़ा"], "Vidisha": ["विदिशा"],
    "Sehore": ["सीहोर"], "Raisen": ["रायसेन"], "Hoshangabad": ["होशंगाबाद"],
    "Narmadapuram": ["नर्मदापुरम"], "Betul": ["बैतूल"], "Harda": ["हरदा"],
    "Khandwa": ["खंडवा"], "Khargone": ["खरगोन"], "Burhanpur": ["बुरहानपुर"],
    "Barwani": ["बड़वानी"], "Jhabua": ["झाबुआ"], "Alirajpur": ["अलीराजपुर"],
    "Mandsaur": ["मंदसौर"], "Neemuch": ["नीमच"], "Shajapur": ["शाजापुर"],
    "Agar Malwa": ["आगर मालवा"], "Rajgarh": ["राजगढ़"],
    "Ashoknagar": ["अशोकनगर"], "Shivpuri": ["शिवपुरी"], "Datia": ["दतिया"],
    "Bhind": ["भिंड"], "Morena": ["मुरैना"], "Sheopur": ["श्योपुर"],
    "Tikamgarh": ["टीकमगढ़"], "Chhatarpur": ["छतरपुर"], "Damoh": ["दमोह"],
    "Narsinghpur": ["नरसिंहपुर"], "Seoni": ["सिवनी"], "Mandla": ["मंडला"],
    "Dindori": ["डिंडोरी"], "Balaghat": ["बालाघाट"], "Shahdol": ["शहडोल"],
    "Umaria": ["उमरिया"], "Anuppur": ["अनूपपुर"], "Sidhi": ["सीधी"],
    "Singrauli": ["सिंगरौली"], "Maihar": ["मैहर"], "Niwari": ["निवाड़ी"],
    # Bihar
    "Bihar": ["बिहार"], "Patna": ["पटना"], "Bhagalpur": ["भागलपुर"],
    "Muzaffarpur": ["मुजफ्फरपुर"], "Darbhanga": ["दरभंगा"],
    "Purnia": ["पूर्णिया"], "Bhojpur": ["भोजपुर"], "Begusarai": ["बेगूसराय"],
    "Katihar": ["कटिहार"], "Munger": ["मुंगेर"], "Chhapra": ["छपरा"],
    "Saran": ["सारण"], "Samastipur": ["समस्तीपुर"], "Motihari": ["मोतिहारी"],
    "Champaran": ["चंपारण"], "Bettiah": ["बेतिया"], "Siwan": ["सीवान"],
    "Gopalganj": ["गोपालगंज"], "Vaishali": ["वैशाली"], "Hajipur": ["हाजीपुर"],
    "Sitamarhi": ["सीतामढ़ी"], "Sheohar": ["शिवहर"], "Madhubani": ["मधुबनी"],
    "Supaul": ["सुपौल"], "Araria": ["अररिया"], "Kishanganj": ["किशनगंज"],
    "Madhepura": ["मधेपुरा"], "Saharsa": ["सहरसा"], "Khagaria": ["खगड़िया"],
    "Nalanda": ["नालंदा"], "Biharsharif": ["बिहारशरीफ"], "Nawada": ["नवादा"],
    "Jehanabad": ["जहानाबाद"], "Arwal": ["अरवल"], "Jamui": ["जमुई"],
    "Lakhisarai": ["लखीसराय"], "Sheikhpura": ["शेखपुरा"],
    "Rohtas": ["रोहतास"], "Sasaram": ["सासाराम"], "Buxar": ["बक्सर"],
    "Kaimur": ["कैमूर"],
    # Rajasthan
    "Rajasthan": ["राजस्थान"], "Jaipur": ["जयपुर"], "Jodhpur": ["जोधपुर"],
    "Udaipur": ["उदयपुर"], "Ajmer": ["अजमेर"], "Bikaner": ["बीकानेर"],
    "Alwar": ["अलवर"], "Bharatpur": ["भरतपुर"], "Sikar": ["सीकर"],
    "Jhunjhunu": ["झुंझुनूं", "झुंझुनू"], "Churu": ["चूरू"],
    "Ganganagar": ["गंगानगर"], "Hanumangarh": ["हनुमानगढ़"],
    "Nagaur": ["नागौर"], "Barmer": ["बाड़मेर"], "Jaisalmer": ["जैसलमेर"],
    "Jalore": ["जालोर"], "Sirohi": ["सिरोही"], "Bhilwara": ["भीलवाड़ा"],
    "Chittorgarh": ["चित्तौड़गढ़"], "Rajsamand": ["राजसमंद"],
    "Dungarpur": ["डूंगरपुर"], "Banswara": ["बांसवाड़ा"], "Baran": ["बारां"],
    "Jhalawar": ["झालावाड़"], "Sawai Madhopur": ["सवाई माधोपुर"],
    "Karauli": ["करौली"], "Dholpur": ["धौलपुर"], "Dausa": ["दौसा"],
    "Tonk": ["टोंक"],
    # Haryana + Delhi
    "Haryana": ["हरियाणा"], "Gurugram": ["गुरुग्राम"], "Gurgaon": ["गुड़गांव"],
    "Faridabad": ["फरीदाबाद"], "Panipat": ["पानीपत"], "Ambala": ["अंबाला"],
    "Yamunanagar": ["यमुनानगर"], "Rohtak": ["रोहतक"], "Hisar": ["हिसार"],
    "Karnal": ["करनाल"], "Sonipat": ["सोनीपत"], "Panchkula": ["पंचकूला"],
    "Bhiwani": ["भिवानी"], "Sirsa": ["सिरसा"], "Jind": ["जींद"],
    "Kaithal": ["कैथल"], "Kurukshetra": ["कुरुक्षेत्र"],
    "Fatehabad": ["फतेहाबाद"], "Rewari": ["रेवाड़ी"],
    "Mahendragarh": ["महेंद्रगढ़"], "Narnaul": ["नारनौल"],
    "Jhajjar": ["झज्जर"], "Palwal": ["पलवल"], "Nuh": ["नूंह"],
    "Mewat": ["मेवात"], "Charkhi Dadri": ["चरखी दादरी"],
    "Delhi": ["दिल्ली"], "New Delhi": ["नई दिल्ली"],
    # Jharkhand
    "Jharkhand": ["झारखंड"], "Ranchi": ["रांची", "राँची"],
    "Jamshedpur": ["जमशेदपुर"], "Dhanbad": ["धनबाद"], "Bokaro": ["बोकारो"],
    "Deoghar": ["देवघर"], "Hazaribagh": ["हजारीबाग"], "Giridih": ["गिरिडीह"],
    "Dumka": ["दुमका"], "Palamu": ["पलामू"], "Daltonganj": ["डाल्टनगंज"],
    "Chatra": ["चतरा"], "Koderma": ["कोडरमा"], "Jamtara": ["जामताड़ा"],
    "Sahibganj": ["साहिबगंज"], "Pakur": ["पाकुड़"], "Godda": ["गोड्डा"],
    "Lohardaga": ["लोहरदगा"], "Gumla": ["गुमला"], "Simdega": ["सिमडेगा"],
    "Khunti": ["खूंटी"], "Saraikela": ["सरायकेला"], "Chaibasa": ["चाईबासा"],
    "Singhbhum": ["सिंहभूम"], "Ramgarh": ["रामगढ़"], "Latehar": ["लातेहार"],
    "Garhwa": ["गढ़वा"],
    # Chhattisgarh
    "Chhattisgarh": ["छत्तीसगढ़"], "Raipur": ["रायपुर"],
    "Bilaspur": ["बिलासपुर"], "Durg": ["दुर्ग"], "Bhilai": ["भिलाई"],
    "Korba": ["कोरबा"], "Rajnandgaon": ["राजनांदगांव"], "Raigarh": ["रायगढ़"],
    "Jagdalpur": ["जगदलपुर"], "Bastar": ["बस्तर"], "Ambikapur": ["अंबिकापुर"],
    "Surguja": ["सरगुजा"], "Dhamtari": ["धमतरी"], "Mahasamund": ["महासमुंद"],
    "Kanker": ["कांकेर"], "Kawardha": ["कवर्धा"], "Janjgir": ["जांजगीर"],
    "Champa": ["चांपा"], "Mungeli": ["मुंगेली"], "Balod": ["बालोद"],
    "Baloda Bazar": ["बलौदा बाजार"], "Bemetara": ["बेमेतरा"],
    "Gariaband": ["गरियाबंद"], "Kondagaon": ["कोंडागांव"], "Sukma": ["सुकमा"],
    "Dantewada": ["दंतेवाड़ा"], "Narayanpur": ["नारायणपुर"],
    "Jashpur": ["जशपुर"], "Surajpur": ["सूरजपुर"],
    # Uttarakhand
    "Uttarakhand": ["उत्तराखंड"], "Dehradun": ["देहरादून"],
    "Haridwar": ["हरिद्वार"], "Rishikesh": ["ऋषिकेश"], "Roorkee": ["रुड़की"],
    "Nainital": ["नैनीताल"], "Haldwani": ["हल्द्वानी"],
    "Udham Singh Nagar": ["उधम सिंह नगर"], "Rudrapur": ["रुद्रपुर"],
    "Almora": ["अल्मोड़ा"], "Pithoragarh": ["पिथौरागढ़"],
    "Champawat": ["चंपावत"], "Bageshwar": ["बागेश्वर"], "Chamoli": ["चमोली"],
    "Rudraprayag": ["रुद्रप्रयाग"], "Tehri": ["टिहरी"], "Pauri": ["पौड़ी"],
    "Uttarkashi": ["उत्तरकाशी"],
    # Himachal Pradesh
    "Himachal Pradesh": ["हिमाचल प्रदेश"], "Shimla": ["शिमला"],
    "Kangra": ["कांगड़ा"], "Dharamshala": ["धर्मशाला"], "Solan": ["सोलन"],
    "Kullu": ["कुल्लू"], "Manali": ["मनाली"], "Una": ["ऊना"],
    "Chamba": ["चंबा"], "Sirmaur": ["सिरमौर"], "Nahan": ["नाहन"],
    "Kinnaur": ["किन्नौर"], "Lahaul": ["लाहौल"], "Spiti": ["स्पीति"],
    "Keylong": ["केलांग"],
    # Jammu & Kashmir + Ladakh (Hindi press forms)
    "Jammu": ["जम्मू"], "Kashmir": ["कश्मीर"], "Srinagar": ["श्रीनगर"],
    "Anantnag": ["अनंतनाग"], "Baramulla": ["बारामूला"],
    "Udhampur": ["उधमपुर"], "Kathua": ["कठुआ"], "Rajouri": ["राजौरी"],
    "Poonch": ["पुंछ"], "Doda": ["डोडा"], "Ladakh": ["लद्दाख"],
    "Leh": ["लेह"], "Kargil": ["करगिल", "कारगिल"],
}


def office_places(office: str) -> list[str]:
    """Every place name that counts as this office's region: the state
    name(s) and their districts/major cities. An office this module does
    not know matches on its own name alone, so a custom office still
    works, just narrowly."""
    states = OFFICE_STATES.get(office)
    if not states:
        return [office]
    seen: set[str] = set()
    places: list[str] = []
    for st in states:
        for term in STATE_NAMES.get(st, [st]) + STATE_DISTRICTS.get(st, []):
            if term.lower() not in seen:
                seen.add(term.lower())
                places.append(term)
    # Marathi/Hindi press writes these names in Devanagari; add those
    # spellings so a regional-language story places itself too.
    for term in list(places):
        for dev in DEVANAGARI.get(term, []):
            if dev not in seen:
                seen.add(dev)
                places.append(dev)
    return places


def describe(office: str) -> str:
    """One line saying what region an office covers, for the RD View."""
    states = OFFICE_STATES.get(office)
    if not states:
        return office
    pretty = [s.replace(" (excluding Vidarbha)", " excluding Vidarbha")
               .replace(" (Vidarbha)", " — Vidarbha districts")
              for s in states]
    return ", ".join(pretty)
